#!/bin/sh
# /etc/init.d/power-monitor

case "$1" in
	start)
		echo "Starting power monitor..."
		echo 7 > /sys/class/gpio/export
		echo falling > /sys/class/gpio/gpio7/edge
		python /root/power/monitor.py &
		;;
	stop)
		echo "Stopping power monitor..."
		kill `ps -ef | grep monitor.py | grep -v grep | awk '{print $2}'`
		killall gpio-irq
		;;
	*)
		echo "Usage: /etc/init.d/power-monitor (start|stop)"
		exit 1
		;;
esac

exit 0
